config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#index'

  devise_for :users
  resources :posts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_one :userparam
         has_many :posts

end

app/models/userparam.rb
class Userparam < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  	before_action :authenticate_user!
  	before_action :find_post, only: [:show, :edit, :update, :destroy]
  def index
  end
  def new
  	@post = Post.new
  end
  def create
  	@post = current_user.posts.build(post_params)
  	if @post.save
  		redirect_to root_path
  	end
  end
  def show
  	
  end
  def edit
  	
  end
  def update
  	
     @post.update(post_params)
     if @post.save
     	redirect_to root_path(@post.id)
     end
     
  end
  def destroy
  	
    @post.destroy
    redirect_to root_path
  end 
  def find_post
  	@post = Post.find_by(id: params[:id])
  end
  private 
  def post_params
  	params.require(:post).permit(:user_id, :title, :body)
  end
end

app/controllers/userparam_controller.rb
class UserparamController < ApplicationController
	before_action :authenticate_user!

  def edit
  	
  end
  def update
  	
     
     end
     
  end
  def new
  def destroy
  
  end 
  def find_post

  end
  private 
  def userparam_params
  
  end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/userparam_helper.rb
module UserparamHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>My site</h1>
<p>This is my site</p>

<%= link_to "Login", new_user_session_path %>
<%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% if !current_user.nil? %>
	<%= link_to "Profile"%>
<% end %>
<hr>
<%= link_to "Create new post", new_post_path %>
<% if @posts == [] %>
	<p>Create new post</p>
	<% else %>
		<% @posts.each do |post|%>
		<p>User <%= post.user.email %> write: %>
		<b><%= post.title %></b><br />
		<%= post.body %></p>
		<p><%= link_to "Read More", post_path(post.id) %></p>
	<% end %>
<% end %>
	

app/views/posts/edit.html.erb
<%= form_for @post, url: post_path(@post.id) do |f| %>


<%= f.text_field :title%><br>
<%= f.text_field :body%><br>
<%= f.submit "Create" %>
	
<% end %>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<%= form_for @post, url: posts_path do |f| %>


<%= f.text_field :title%><br>
<%= f.text_field :body%><br>
<%= f.submit "Create" %>
	
<% end %>

app/views/posts/show.html.erb
User: <%= @post.user.email %><br />
Title:<%= @post.title %><br />
Body: <%= @post.body %><br />
<% if @post.user_id == current_user.id %>

<%= link_to "Edit", edit_post_path(@post.id) %><br />

<%= link_to "Delete", post_path(@post.id), method: :delete %><br />

<% end %>

app/views/userparam/edit.html.erb
<%= form_for @userparam, url: userparam_path(@userparam.id) do |f| %>


<%= f.text_field :title%><br>
<%= f.text_field :body%><br>
<%= f.submit "Create" %>
	
<% end %>

app/views/userparam/index.html.erb
<h1>Profile#index</h1>
<p>Find me in app/views/userparam/index.html.erb</p>

app/views/userparam/new.html.erb
<%= form_for @userparam, url: userparam_path do |f| %>


<%= f.text_field :title%><br>
<%= f.text_field :body%><br>
<%= f.submit "Create" %>
	
<% end %>

app/views/userparam/show.html.erb
User: <%= @userparam.user.email %><br />
Title:<%= @userparam.title %><br />
Body: <%= @userparam.body %><br />
<% if @userparam.user_id == current_user.id %>

<%= link_to "Edit", edit_userparam_path(@userparam.id) %><br />

<%= link_to "Delete", userparam_path(@post.id), method: :delete %><br />

<% end %>